language: ruby
cache: bundler
sudo: false
rvm:
  - 2.2.0
before_script:
  - cp config/database.yml.example config/database.yml
  - cp config/initializers/0_glitterconfig.rb.example config/initializers/0_glitterconfig.rb
  - psql -c 'create database travis_ci_test;' -U postgres
  - RAILS_ENV=test bundle exec rake --trace db:migrate
script:
  - bundle exec rubocop --config .rubocop.yml
  - RAILS_ENV=test xvfb-run bundle exec rspec
  - bundle exec haml-lint app/views/
